# Generated by Django 4.0.4 on 2022-06-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=0.6, max_digits=6),
            preserve_default=False,
        ),
    ]
