# Generated by Django 4.0.4 on 2022-06-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_charge_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='Operator',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='charge',
            name='Service_type',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
