# Generated by Django 4.0.4 on 2022-06-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_alter_charge_operator_alter_charge_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='calculated',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
