# Generated by Django 4.0.4 on 2022-06-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_charge_calculated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
