# Generated by Django 4.0.4 on 2022-06-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Service_name',
            field=models.CharField(max_length=100),
        ),
    ]
