# Generated by Django 4.0.5 on 2022-06-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_alter_charge_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Service_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
