# Generated by Django 4.0.5 on 2022-06-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0009_service_live'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
