# Generated by Django 4.0.5 on 2022-06-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0011_diot_alter_charge_calculated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='calculated',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
