# Generated by Django 4.0.5 on 2022-07-05 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0014_alter_service_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='live_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='Operator',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
