# Generated by Django 4.0.5 on 2022-07-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0015_service_live_on_alter_service_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='HPMNTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(max_length=100, unique=True)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
