# Generated by Django 4.0.5 on 2022-07-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0017_hpmntable_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpmntable',
            name='call_type',
            field=models.CharField(max_length=100),
        ),
    ]
