# Generated by Django 4.0.5 on 2022-07-26 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0020_alter_service_live_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='live_on',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
