# Generated by Django 4.0.4 on 2022-06-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=50)),
                ('Operators', models.TextField()),
                ('CountryCode', models.PositiveIntegerField()),
            
            ],
        ),
    ]
