# Generated by Django 4.0.4 on 2022-06-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='operator_ndcs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndc', models.CharField(max_length=100)),
                ('operator_id', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='operator',
            name='country_id',
        ),
    ]
