# Generated by Django 4.0.4 on 2022-06-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_operator_country_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='Zone',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operator',
            name='country_id',
            field=models.SmallIntegerField(),
        ),
    ]
