# Generated by Django 4.0.4 on 2022-06-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_partner_zone_alter_operator_country_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='Zone',
            field=models.TextField(default='Ecowas'),
        ),
    ]
