# Generated by Django 4.0.4 on 2022-06-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_alter_partner_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='country_id',
            field=models.CharField(max_length=50),
        ),
    ]
