# Generated by Django 4.0.4 on 2022-06-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_partner_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='test',
        ),
        migrations.AlterField(
            model_name='partner',
            name='Operators',
            field=models.TextField(blank=True, default='QCELL'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
