# Generated by Django 4.0.4 on 2022-06-08 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_remove_partner_test_alter_partner_operators_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='Operators',
        ),
    ]
