# Generated by Django 4.0.4 on 2022-06-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_remove_partner_operators'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='Operators',
            field=models.TextField(blank=True, default='QCELL'),
        ),
    ]
