# Generated by Django 4.0.4 on 2022-06-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0013_partner_operators'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='LocalCurrency',
            field=models.CharField(default='GMD', max_length=3),
        ),
    ]
