# Generated by Django 4.0.4 on 2022-06-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0014_partner_localcurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='CountryCode',
            field=models.PositiveIntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='partner',
            name='LocalCurrency',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
