# Generated by Django 4.0.4 on 2022-06-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0015_alter_partner_countrycode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='Country',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='CountryCode',
            field=models.PositiveIntegerField(),
        ),
    ]
