# Generated by Django 4.0.4 on 2022-06-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0016_alter_partner_country_alter_partner_countrycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='Country',
            field=models.CharField(max_length=50),
        ),
    ]
