# Generated by Django 4.0.4 on 2022-06-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0018_alter_partner_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange_Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='operator',
            name='service_type',
        ),
    ]
