# Generated by Django 4.0.4 on 2022-06-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0019_exchange_rates_remove_operator_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='country_id',
            field=models.CharField(blank=True, default='ycor', max_length=50),
        ),
    ]
