# Generated by Django 4.0.4 on 2022-06-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0020_alter_operator_country_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='country_id',
            field=models.CharField(default='ycor', max_length=50),
        ),
    ]
