# Generated by Django 4.0.4 on 2022-06-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0021_alter_operator_country_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='country_id',
            field=models.CharField(max_length=50),
        ),
    ]
