# Generated by Django 4.0.4 on 2022-06-09 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0024_delete_exchange_rates_operator_service_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='rp_currency',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='service_type',
        ),
    ]
