# Generated by Django 4.0.4 on 2022-06-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0025_remove_operator_rp_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='Country',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
