# Generated by Django 4.0.4 on 2022-06-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0026_alter_partner_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='exchange_rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocalCurrency', models.CharField(blank=True, max_length=3)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AlterField(
            model_name='operator',
            name='country_id',
            field=models.CharField(blank='True', default='ysl', max_length=50),
        ),
    ]
