# Generated by Django 4.0.4 on 2022-06-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0027_exchange_rate_alter_operator_country_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange_rate',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
