# Generated by Django 4.0.4 on 2022-06-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0030_alter_exchange_rate_rate_alter_partner_localcurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange_rate',
            name='LocalCurrency',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='partner',
            name='LocalCurrency',
            field=models.CharField(default='GMD', max_length=3),
        ),
    ]
