# Generated by Django 4.0.4 on 2022-06-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0031_alter_exchange_rate_localcurrency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='country_id',
            field=models.CharField(blank='True', default='Gambia', max_length=50),
        ),
        migrations.AlterField(
            model_name='partner',
            name='Country',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
