# Generated by Django 4.0.4 on 2022-06-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0032_alter_operator_country_id_alter_partner_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange_rate',
            name='rate',
            field=models.DecimalField(decimal_places=5, max_digits=11),
        ),
    ]
