# Generated by Django 4.0.4 on 2022-06-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0033_alter_exchange_rate_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange_rate',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='partner',
            name='LocalCurrency',
            field=models.CharField(blank=True, default='GMD', max_length=3),
        ),
    ]
