# Generated by Django 4.0.4 on 2022-06-13 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0035_gambia_tax_remove_partner_operators'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gambia_Tax',
        ),
    ]
