# Generated by Django 4.0.4 on 2022-06-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0036_delete_gambia_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='foreign_tax',
            field=models.IntegerField(default=0),
        ),
    ]
