# Generated by Django 4.0.4 on 2022-06-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0037_operator_foreign_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gambia_tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.IntegerField()),
            ],
        ),
    ]
