# Generated by Django 4.0.4 on 2022-06-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0038_gambia_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gambia_tax',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
