# Generated by Django 4.0.4 on 2022-06-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0040_alter_operator_foreign_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='gambia_tax',
            name='markup',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=4),
            preserve_default=False,
        ),
    ]
