# Generated by Django 4.0.5 on 2022-06-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0042_alter_operator_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange_rate',
            name='LocalCurrency',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
