# Generated by Django 4.0.5 on 2022-06-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0043_alter_exchange_rate_localcurrency'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='LocalCurrency',
            field=models.CharField(blank=True, default='GMD', max_length=3),
        ),
    ]
