# Generated by Django 4.0.5 on 2022-06-24 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0044_operator_localcurrency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='LocalCurrency',
        ),
    ]
