# Generated by Django 4.0.5 on 2022-06-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0046_alter_operator_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='standard_iot',
            field=models.CharField(blank=b'I01\n', max_length=1000),
        ),
    ]
