# Generated by Django 4.0.5 on 2022-06-30 10:40

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0047_alter_operator_standard_iot'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='dropdown',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
