# Generated by Django 4.0.5 on 2022-06-30 10:46

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0048_partner_dropdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='Country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
