# Generated by Django 4.0.5 on 2022-06-30 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0049_alter_partner_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='dropdown',
        ),
    ]
