# Generated by Django 4.0.5 on 2022-06-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0050_remove_partner_dropdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='diot',
        ),
    ]
