# Generated by Django 4.0.5 on 2022-06-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0051_remove_operator_diot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='agreement_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='operator',
            name='standard_iot',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
