# Generated by Django 4.0.5 on 2022-07-18 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0052_alter_operator_agreement_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='mcc_mnc',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
