# Generated by Django 4.0.5 on 2022-07-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0053_alter_operator_mcc_mnc'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='direction',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
